import type { Direction, Professor, Source } from '../shared/types.js';

// A small, reviewed starting collection, not a live opportunity database.
// Change checkedAt only after opening and reviewing the referenced page.
const checkedAt = '2026-10-03';
const university = 'University of Minnesota Twin Cities';
const source = (title: string, url: string): Source => ({ title, url, checkedAt });

export const directions: Direction[] = [
  {
    id: 'human-computer-interaction',
    title: 'Human–Computer Interaction',
    field: 'Computer science × Design × Psychology',
    question: 'How can technology work better for the people using it?',
    description: 'Study how people use digital tools, uncover where they struggle, and design and evaluate better experiences. Research can involve observation, interviews, prototypes, and careful comparison of alternatives.',
    why: 'A direction to try if you enjoy understanding people and making technology easier to use. You can begin with a paper prototype before learning advanced programming.',
    activities: [
      'Walk through a familiar app and document three moments that could confuse a new user.',
      'Sketch two versions of one screen and explain the tradeoff between them.',
      'Read a study and identify its research question, participants, and evaluation method.',
    ],
    firstStep: 'Choose one campus website. Sketch a clearer version of one screen and annotate three design decisions.',
    skills: ['Observation and interviewing', 'Prototyping', 'Research methods', 'Basic statistics', 'Introductory programming (useful for interactive prototypes)'],
    resources: [{
      title: 'MIT OpenCourseWare: User Interface Design and Implementation',
      url: 'https://ocw.mit.edu/courses/6-831-user-interface-design-and-implementation-spring-2011/',
      description: 'Start with the usability and user-centered design materials. The full course also includes programming; you do not need to finish it to explore HCI.',
    }],
    tags: ['hci', 'human computer interaction', 'design', 'ux', 'ui', 'people', 'psychology', 'accessibility', 'interfaces', 'apps', 'computer science', 'cs', 'social computing', 'technology'],
  },
  {
    id: 'recommender-systems',
    title: 'Recommender Systems',
    field: 'Computer science × Data science',
    question: 'How do we help people discover something they will value?',
    description: 'Investigate how systems choose movies, music, articles, or opportunities for a person. Explore how preference data, algorithms, and interface choices affect usefulness, diversity, and fairness.',
    why: 'A direction to try if you are curious about personalization, machine learning, or the way online platforms shape what people discover.',
    activities: [
      'Create a small, fictional user–item table and compare popularity with personalized suggestions.',
      'Describe when an accurate prediction might still make an unhelpful recommendation.',
      'Compare two ranking rules using a held-out example rather than evaluating on training data.',
    ],
    firstStep: 'Make a table of five fictional people and five movies. Write a popularity rule and a similarity rule, then compare who each serves well.',
    skills: ['Python basics', 'Tables and data cleaning', 'Introductory statistics', 'Linear algebra', 'Evaluation and train/test separation'],
    resources: [{
      title: 'Google: Recommendations — what and why?',
      url: 'https://developers.google.com/machine-learning/recommendation/overview',
      description: 'An accessible introduction to recommendation problems, with further lessons on content-based and collaborative approaches.',
    }],
    tags: ['recommendations', 'recommender', 'recommendation', 'personalization', 'music', 'movies', 'machine learning', 'ml', 'ai', 'algorithms', 'python', 'data science', 'computer science', 'cs', 'ranking'],
  },
  {
    id: 'learning-analytics',
    title: 'Learning Analytics & Learning Sciences',
    field: 'Education × Psychology × Data science',
    question: 'How can evidence help us understand and support learning?',
    description: 'Connect questions about how students learn with observations, learning activities, and data. You might study feedback, debugging, collaboration, or how a learning tool supports understanding.',
    why: 'A direction to try if you enjoy teaching, learning, games, or building educational tools. Both qualitative observations and quantitative analysis can contribute.',
    activities: [
      'Compare two explanations of the same concept and describe what each asks a learner to do.',
      'Create fictional learning records and distinguish activity counts from evidence of understanding.',
      'Read a learning study and identify the learning theory behind the measured outcome.',
    ],
    firstStep: 'Pick a concept you recently learned. Draft two kinds of feedback for a common mistake and explain what evidence would show that each helps.',
    skills: ['Learning theory', 'Research methods', 'Data visualization', 'Basic statistics', 'Privacy-aware study design'],
    resources: [{
      title: 'SoLAR: What is Learning Analytics?',
      url: 'https://www.solaresearch.org/about/what-is-learning-analytics/',
      description: 'The research society’s introduction to learning analytics, its uses, and questions about educational data and ethics.',
    }],
    tags: ['education', 'teaching', 'tutoring', 'learning', 'students', 'edtech', 'games', 'psychology', 'feedback', 'data science', 'computer science', 'cs', 'analytics', 'learning science'],
  },
  {
    id: 'bioinformatics',
    title: 'Bioinformatics & Computational Biology',
    field: 'Biology × Computer science',
    question: 'What can biological data tell us about how living systems work?',
    description: 'Use computation to investigate genes, proteins, and biological networks. Begin by understanding a biological question and the meaning of the data before choosing an algorithm.',
    why: 'A direction to try if you like biology and patterns, or want to connect programming with questions about living systems. An interest in either side can be a starting point.',
    activities: [
      'Explore a public biological database and distinguish a gene identifier from a measured value.',
      'Sketch how interacting genes could affect a cell’s behavior.',
      'Inspect a small published data table and document its variables and missing information.',
    ],
    firstStep: 'Read the introductory bioinformatics lesson. Choose one public database it introduces and write a question that its data could help investigate.',
    skills: ['Introductory genetics', 'Python or R', 'Statistics', 'Data cleaning', 'Biological interpretation'],
    resources: [{
      title: 'EMBL-EBI: Bioinformatics for the terrified',
      url: 'https://www.ebi.ac.uk/training/online/courses/bioinformatics-terrified/',
      description: 'A free overview of biological databases and bioinformatics. Basic life-science knowledge helps; no prior database-tool experience is assumed.',
    }],
    tags: ['biology', 'bioinformatics', 'computational biology', 'genetics', 'genomics', 'genes', 'proteins', 'cells', 'health', 'data science', 'machine learning', 'python', 'computer science', 'cs'],
  },
  {
    id: 'ecology-conservation',
    title: 'Ecology & Conservation',
    field: 'Biology × Environmental science',
    question: 'How do changes in biodiversity affect the places we live?',
    description: 'Study interactions among organisms and their environments. Researchers combine field observations, experiments, and data analysis to investigate biodiversity and environmental change.',
    why: 'A direction to try if you care about climate, wildlife, plants, or the outdoors. You can explore either field-based questions or ecological data analysis.',
    activities: [
      'Draw a small ecosystem and propose how one environmental change could affect it.',
      'Plot an example ecological dataset and describe variation rather than only its average.',
      'Read a field experiment and identify what was changed, measured, and held comparable.',
    ],
    firstStep: 'Choose a local ecosystem. Write one question about biodiversity and list what you would need to measure to answer it.',
    skills: ['Ecology foundations', 'Careful observation', 'Experimental design', 'R or spreadsheet analysis', 'Data visualization'],
    resources: [{
      title: 'Data Carpentry: R for Ecologists',
      url: 'https://datacarpentry.github.io/R-ecology-lesson/',
      description: 'Hands-on ecological data lessons beginning with R and RStudio. No programming background is assumed; setup is needed for the exercises.',
    }],
    tags: ['ecology', 'conservation', 'biology', 'environment', 'environmental', 'climate', 'biodiversity', 'plants', 'wildlife', 'animals', 'nature', 'outdoors', 'sustainability', 'fieldwork'],
  },
  {
    id: 'neuroscience',
    title: 'Neuroscience & Decision-Making',
    field: 'Biology × Psychology × Computation',
    question: 'How do brains learn, remember, and make decisions?',
    description: 'Explore links between brain activity, behavior, and computational explanations. Research may involve experiments, analysis of existing recordings, or models that explain a pattern of choices.',
    why: 'A direction to try if you are curious about the brain, memory, behavior, or the connections between biological and artificial intelligence.',
    activities: [
      'Compare two explanations for why a person repeats a familiar choice.',
      'Read a study figure and distinguish a behavioral measure from a brain measure.',
      'Sketch a simple learning model and predict how changing its assumptions affects choices.',
    ],
    firstStep: 'Watch part of the introductory Human Brain lecture. Write one question about decision-making and two different ways a researcher could investigate it.',
    skills: ['Introductory neuroscience', 'Psychology foundations', 'Statistics', 'Experimental design', 'Python or R for computational work'],
    resources: [{
      title: 'MIT OpenCourseWare: The Human Brain',
      url: 'https://ocw.mit.edu/courses/9-13-the-human-brain-spring-2019/',
      description: 'Undergraduate lectures, notes, and assignments connecting cognitive abilities with brain research. Start with the introduction.',
    }],
    tags: ['neuroscience', 'brain', 'memory', 'cognition', 'cognitive science', 'decision', 'decisions', 'behavior', 'psychology', 'biology', 'learning', 'computational', 'health'],
  },
  {
    id: 'robotics',
    title: 'Robotics & Intelligent Systems',
    field: 'Computer science × Engineering',
    question: 'How can a robot perceive its surroundings and act effectively?',
    description: 'Connect sensing, geometry, planning, and control. Applications can range from assisting people to monitoring fields or automating agricultural tasks; simulations offer a practical starting point.',
    why: 'A direction to try if you like building things, spatial puzzles, engineering, or applying code in the physical world. You can explore a planning problem without buying hardware.',
    activities: [
      'Draw a map and compare routes a robot could take around obstacles.',
      'List the sensors and information a robot would need for a simple task.',
      'Implement or hand-simulate a grid search and document a case where it fails.',
    ],
    firstStep: 'Draw a 6-by-6 grid with obstacles, a start, and a goal. Find a route, then explain what changes if the robot is wider than one square.',
    skills: ['Programming fundamentals', 'Geometry and linear algebra', 'Algorithms', 'Basic mechanics', 'Simulation and evaluation'],
    resources: [{
      title: 'Northwestern: Modern Robotics — Foundations of Robot Motion',
      url: 'https://modernrobotics.northwestern.edu/nu-gm-book-resource/foundations-of-robot-motion/',
      description: 'Free video supplements introducing configuration space and robot motion. Begin with the overview; later material uses linear algebra and mechanics.',
    }],
    tags: ['robotics', 'robots', 'engineering', 'mechanical', 'electrical', 'hardware', 'building', 'computer vision', 'automation', 'agriculture', 'algorithms', 'computer science', 'cs', 'ai'],
  },
  {
    id: 'social-behavioral-science',
    title: 'Social & Behavioral Science',
    field: 'Psychology × Society × Research methods',
    question: 'How do people, communities, and social contexts shape one another?',
    description: 'Investigate behavior, identity, culture, or social relationships through well-defined questions and evidence. Methods include qualitative analysis, surveys, experiments, and examination of how research itself is conducted.',
    why: 'A direction to try if you enjoy asking why people behave differently across situations, reading and writing, or examining assumptions about society.',
    activities: [
      'Turn an everyday observation into a question that could be investigated with evidence.',
      'Compare an interview approach with a survey approach for the same question.',
      'Read a study and identify whose experiences its sample might miss.',
    ],
    firstStep: 'Write one question about identity or behavior. Define the main concept, name two possible explanations, and sketch a study without collecting anyone’s data.',
    skills: ['Research methods', 'Critical reading', 'Qualitative analysis', 'Basic statistics', 'Ethics and sampling'],
    resources: [{
      title: 'OpenStax Psychology 2e: Psychological Research',
      url: 'https://openstax.org/books/psychology-2e/pages/2-introduction',
      description: 'An open introductory chapter on research approaches, interpreting findings, and ethics. Use it to turn a broad curiosity into a researchable question.',
    }],
    tags: ['psychology', 'sociology', 'social', 'behavior', 'behavioral', 'culture', 'identity', 'society', 'communities', 'people', 'writing', 'interviews', 'humanities', 'research methods'],
  },
];

export const professors: Professor[] = [
  {
    id: 'loren-terveen',
    name: 'Loren Terveen',
    title: 'Professor and Department Head',
    university,
    department: 'Computer Science & Engineering',
    research: 'Studies social computing, interactions between people and technology, bias in intelligent systems, and ethical approaches to research with online communities.',
    tags: ['hci', 'social computing', 'intelligent systems', 'bias', 'online communities', 'design'],
    directionIds: ['human-computer-interaction'],
    fit: 'Explore this profile if you want to connect interface design with questions about online communities and responsible computing.',
    conversationStarter: 'What would be a useful first reading for understanding how researchers study the effects of intelligent tools on online communities?',
    availability: 'unknown',
    sources: [source('UMN CS&E faculty profile', 'https://cse.umn.edu/cs/loren-terveen')],
  },
  {
    id: 'joseph-konstan',
    name: 'Joseph A. Konstan',
    title: 'Distinguished McKnight University Professor',
    university,
    department: 'Computer Science & Engineering',
    research: 'Works on recommendation algorithms and experiences, social computing, and human–computer interaction.',
    tags: ['recommender', 'recommendation', 'personalization', 'hci', 'social computing'],
    directionIds: ['recommender-systems', 'human-computer-interaction'],
    fit: 'Explore this profile if you want to study both recommendation methods and the people who use their suggestions.',
    conversationStarter: 'How can a student begin comparing the quality of recommendations beyond prediction accuracy?',
    availability: 'unknown',
    sources: [source('Joseph A. Konstan — UMN faculty website', 'https://konstan.umn.edu/')],
  },
  {
    id: 'david-deliema',
    name: 'David DeLiema',
    title: 'Associate Professor',
    university,
    department: 'Educational Psychology',
    research: 'Studies how learners and teachers respond to mistakes in computing, mathematics, and science, with related interests in play, spatial reasoning, and classroom interaction.',
    tags: ['learning sciences', 'education', 'debugging', 'play', 'classroom', 'psychology'],
    directionIds: ['learning-analytics', 'social-behavioral-science'],
    fit: 'Offers a learning-sciences perspective on this path, especially questions about debugging and productive responses to mistakes. This is an adjacent match for analytics interests.',
    conversationStarter: 'What should a beginner look for when studying how feedback changes a learner’s approach to debugging?',
    availability: 'unknown',
    sources: [source('UMN Educational Psychology faculty profile', 'https://edpsych.umn.edu/david-deliema')],
  },
  {
    id: 'chad-myers',
    name: 'Chad L. Myers',
    title: 'Professor and Distinguished McKnight University Professor',
    university,
    department: 'Computer Science & Engineering',
    research: 'Develops computational and machine-learning approaches that combine genomic datasets to investigate gene function and relationships within biological networks.',
    tags: ['bioinformatics', 'computational biology', 'genomics', 'genes', 'machine learning', 'networks'],
    directionIds: ['bioinformatics'],
    fit: 'Explore this profile if you want to connect biological questions about genes with computation and data analysis.',
    conversationStarter: 'Which biological concepts would help a student understand what a genetic-interaction network represents?',
    availability: 'unknown',
    sources: [source('UMN CS&E faculty profile', 'https://cse.umn.edu/cs/chad-myers')],
  },
  {
    id: 'forest-isbell',
    name: 'Forest Isbell',
    title: 'Professor',
    university,
    department: 'Ecology, Evolution, and Behavior',
    research: 'Investigates how biodiversity changes affect ecosystem performance and stability, and how environmental pressures alter plant communities, including grasslands and forests.',
    tags: ['ecology', 'biodiversity', 'plants', 'ecosystems', 'climate', 'field experiments'],
    directionIds: ['ecology-conservation'],
    fit: 'Explore this profile if you are drawn to biodiversity, ecosystem questions, or the connection between field experiments and environmental data.',
    conversationStarter: 'What makes a good beginner question about the relationship between plant diversity and ecosystem function?',
    availability: 'unknown',
    sources: [source('UMN College of Biological Sciences faculty profile', 'https://cbs.umn.edu/directory/forest-isbell')],
  },
  {
    id: 'david-redish',
    name: 'A. David Redish',
    title: 'Distinguished McKnight University Professor',
    university,
    department: 'Neuroscience',
    research: 'Studies how interacting neural systems support decisions and behavior, combining experiments with computational models and investigating what happens when these processes are disrupted.',
    tags: ['neuroscience', 'decision-making', 'brain', 'learning', 'memory', 'computational models'],
    directionIds: ['neuroscience'],
    fit: 'Explore this profile if you want to connect decision-making and learning with neural data or computational explanations.',
    conversationStarter: 'What is a useful introductory example of a computational model explaining a pattern of choices?',
    availability: 'unknown',
    sources: [source('UMN Medical School faculty profile', 'https://med.umn.edu/bio/david-redish')],
  },
  {
    id: 'volkan-isler',
    name: 'Volkan Isler',
    title: 'Professor',
    university,
    department: 'Computer Science & Engineering',
    research: 'Works on robot algorithms, agricultural and consumer robotics, computer vision, mapping, and geometric methods for planning where sensors should observe.',
    tags: ['robotics', 'computer vision', 'agriculture', 'geometry', 'planning', 'sensors'],
    directionIds: ['robotics'],
    fit: 'Explore this profile if you want to connect algorithms and perception with robots operating in real environments.',
    conversationStarter: 'Which small simulation would help a beginner understand a planning challenge in agricultural robotics?',
    availability: 'unknown',
    sources: [source('UMN CS&E faculty profile', 'https://cse.umn.edu/cs/volkan-isler')],
  },
  {
    id: 'moin-syed',
    name: 'Moin Syed',
    title: 'Professor and McKnight Presidential Endowed Professor',
    university,
    department: 'Psychology',
    research: 'Focuses on psychological research practices, theory, inference, and open science, with additional work on identity and personality development across cultural contexts.',
    tags: ['psychology', 'identity', 'culture', 'open science', 'research methods', 'meta-science'],
    directionIds: ['social-behavioral-science'],
    fit: 'Explore this profile if you are interested in cultural perspectives on psychology or in how researchers make and evaluate scientific claims.',
    conversationStarter: 'What should a beginning researcher read to understand how sampling and cultural context affect a psychological claim?',
    availability: 'unknown',
    sources: [source('UMN College of Liberal Arts faculty profile', 'https://cla.umn.edu/about/directory/profile/moin')],
  },
];
